<?php
/**
 * Created by PhpStorm.
 * User: Paitoon
 * Date: 02/12/2017
 * Time: 10:28 AM
 */

namespace backend\models;


class PibiDetail extends \common\models\PIBIDetail
{

    public $amount, $rate, $xrate, $listid, $recid;

    public function attributeLabels()
    {
        return [
            'id' => '',
            'Groupid' => '',
            'Shiftid' => '',
            'Empid' => '',
            'Date' => '',
            'Hour' => '',
            'Typeid' => '',
            'Qty' => '',
            'Itemid' => '',
            'Deduct' => '',
            'Totaltire' => '',
        ];
    }

    public function rules()
    {
        //return parent::rules(); // TODO: Change the autogenerated stub
        return [
            [['Groupid', 'Shiftid', 'Hour', 'Typeid', 'Itemid', 'Totaltire', 'amount', 'rate'], 'integer'],
            [['xrate'], 'double'],
            [['Empid', 'listid', 'recid'], 'string'],
            [['Date'], 'safe'],
            [['Qty', 'Deduct'], 'number'],
        ];
    }
}